spring:
  datasource:
    url: "jdbc:postgresql://pg-1:5435/order-service"
    username: postgres
    password: test
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    function:
      definition: orderCreatedFunction

    stream:
      default-binder: kafka
      bindings:
        orderCreatedFunction-out-0:
          destination: order-topic
          content-type: application/json
      kafka:
        binder:
          brokers: kafka:9092
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: "http://eureka:8888/eureka/"
    register-with-eureka: true
    fetch-registry: true